import { KPIGuidanceRule, ManagerRoleTier } from '@/types/managerGuidance';

export const KPI_GUIDANCE_RULES: KPIGuidanceRule[] = [
  {
    kpiCode: 'staff_adequacy_score',
    kpiName: 'Staff Adequacy Score',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review LC headcount at your office. Initiate recruitment if below target band, or re-balance workload if over-staffed.',
      district: 'Review staffing adequacy across district offices. Identify under-staffed branches contributing most to the gap and prioritise recruitment.',
      province: 'Assess province-wide staffing levels. Identify districts with systemic under-staffing and develop a province-level recruitment plan.',
      institution: 'Evaluate institutional staffing strategy. Review whether the target band remains appropriate and align recruitment budgets accordingly.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=staffing',
    category: 'Staffing',
  },
  {
    kpiCode: 'productivity_achievement',
    kpiName: 'Productivity Achievement',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Coach under-performing loan consultants on client acquisition. Review client-product mix and identify cross-sell opportunities.',
      district: 'Identify branches with lowest avg disbursement per LC. Share best practices from top-performing branches and run targeted coaching clinics.',
      province: 'Analyse province-wide productivity trends. Review whether market conditions or portfolio composition are constraining disbursement.',
      institution: 'Evaluate institutional productivity targets. Review incentive structures, product pricing, and marketing support.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=productivity',
    category: 'Performance',
  },
  {
    kpiCode: 'vacancy_impact',
    kpiName: 'Vacancy Impact',
    target: 0,
    warningThreshold: 1,
    criticalThreshold: 3,
    higherIsBetter: false,
    severityRules: {
      healthy: (current) => current === 0,
      low: (current) => current === 1,
      medium: (current) => current === 2,
      high: (current) => current === 3,
      critical: (current) => current > 3,
    },
    recommendedActions: {
      branch: 'Initiate targeted recruitment to fill vacant LC positions. Prioritise branches where user_count is below branch capacity.',
      district: 'Review vacancy distribution across district offices. Coordinate recruitment drives for branches with multiple vacancies.',
      province: 'Assess province-wide vacancy trends. Review whether recruitment pipelines are sufficient to meet growth targets.',
      institution: 'Evaluate institutional vacancy rates. Review HR policies, compensation competitiveness, and employer branding.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=staffing',
    category: 'Staffing',
  },
  {
    kpiCode: 'portfolio_load_balance',
    kpiName: 'Portfolio Load Balance',
    target: 100,
    warningThreshold: 70,
    criticalThreshold: 100,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 100,
      low: (current) => current >= 70 && current < 100,
      medium: (current) => current >= 50 && current < 70,
      high: (current) => current >= 30 && current < 50,
      critical: (current) => current < 30,
    },
    recommendedActions: {
      branch: 'Re-balance client assignments among LCs. Approve controlled top-ups for existing borrowers or re-assign accounts to under-utilised consultants.',
      district: 'Review workload distribution across district offices. Identify branches with extreme over/under-load and re-allocate clients.',
      province: 'Analyse province-wide portfolio concentration. Review whether certain products or regions are creating systemic load imbalances.',
      institution: 'Evaluate institutional portfolio management strategy. Review LC capacity planning and client segmentation policies.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=portfolio',
    category: 'Portfolio',
  },
  {
    kpiCode: 'volume_achievement',
    kpiName: 'Volume Achievement',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Increase client acquisition and disbursement volume. Review pipeline and tighten marketing efforts in the branch area.',
      district: 'Review pipeline health across district offices. Run targeted acquisition campaigns in under-performing branches.',
      province: 'Assess province-wide volume trends. Review whether product mix or market conditions are constraining growth.',
      institution: 'Evaluate institutional volume targets. Review strategic growth plans and resource allocation.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=performance',
    category: 'Performance',
  },
  {
    kpiCode: 'collections_efficiency',
    kpiName: 'Collections Efficiency',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Strengthen collection processes at the branch. Follow up on overdue accounts proactively and improve payment tracking.',
      district: 'Review collection performance across district offices. Identify branches with highest delinquency and deploy targeted recovery interventions.',
      province: 'Assess province-wide collection trends. Review whether portfolio seasoning or economic conditions are driving delinquency.',
      institution: 'Evaluate institutional collection strategy. Review recovery policies, early-warning frameworks, and write-off thresholds.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=recoveries',
    category: 'Recovery',
  },
  {
    kpiCode: 'cash_position_score',
    kpiName: 'Cash Position Score',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Improve cash collection timing and reduce unnecessary expenditures. Monitor liquidity daily and escalate shortfalls.',
      district: 'Review cash flow patterns across district offices. Identify branches with recurring liquidity gaps and provide cash-management support.',
      province: 'Assess province-wide cash position. Review whether disbursement schedules or collection cycles are creating systemic liquidity pressure.',
      institution: 'Evaluate institutional liquidity management. Review treasury policies, contingency funding, and cash-flow forecasting.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=cash',
    category: 'Finance',
  },
  {
    kpiCode: 'recovery_performance',
    kpiName: 'Recovery Performance',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review recovery performance at the branch. Identify delinquent accounts, prioritise high-value follow-ups, and strengthen field collections.',
      district: 'Analyse district recovery rates. Deploy specialised recovery teams to the worst-performing branches and review restructuring options.',
      province: 'Assess province-wide recovery performance. Review whether external economic factors or internal credit policy are driving delinquency.',
      institution: 'Evaluate institutional recovery strategy. Review early-delinquency frameworks, write-off policies, and recovery outsourcing.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=recoveries',
    category: 'Recovery',
  },
  {
    kpiCode: 'month1_default_performance',
    kpiName: 'Month-1 Default Performance',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Strengthen first-month follow-up processes. Review client onboarding quality and early-payment communication.',
      district: 'Review first-month default trends across district offices. Identify branches with weak onboarding and provide targeted training.',
      province: 'Assess province-wide early-default patterns. Review credit assessment criteria and disbursement controls.',
      institution: 'Evaluate institutional early-default strategy. Review scoring models, disbursement guardrails, and early-warning systems.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=quality',
    category: 'Quality',
  },
  {
    kpiCode: 'portfolio_quality',
    kpiName: 'Portfolio Quality',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review portfolio quality at the branch. Focus on reducing PAR30+ and improving collateral coverage.',
      district: 'Analyse portfolio quality across district offices. Identify branches with deteriorating asset quality and intervene early.',
      province: 'Assess province-wide portfolio trends. Review whether product mix or client selection is driving quality deterioration.',
      institution: 'Evaluate institutional portfolio quality framework. Review risk appetite, credit policy, and provisioning adequacy.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=quality',
    category: 'Quality',
  },
  {
    kpiCode: 'efficiency_ratio',
    kpiName: 'Efficiency Ratio (CIR)',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review branch operating efficiency. Reduce non-productive expenditures and streamline client service processes.',
      district: 'Analyse efficiency across district offices. Identify branches with high cost-to-income ratios and share best practices.',
      province: 'Assess province-wide efficiency trends. Review whether shared services or centralisation could reduce duplication.',
      institution: 'Evaluate institutional efficiency strategy. Review technology investments, process automation, and organisational design.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=efficiency',
    category: 'Efficiency',
  },
  {
    kpiCode: 'growth_trajectory',
    kpiName: 'Growth Trajectory',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review branch growth trajectory. Identify new-client acquisition gaps and develop targeted growth initiatives.',
      district: 'Analyse growth patterns across district offices. Support under-performing branches with mentorship and market intelligence.',
      province: 'Assess province-wide growth trajectory. Review market penetration and expansion opportunities.',
      institution: 'Evaluate institutional growth strategy. Review market segmentation, product roadmap, and geographic expansion plans.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=growth',
    category: 'Growth',
  },
  {
    kpiCode: 'long_term_delinquency',
    kpiName: 'Long-Term Delinquency',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review long-term delinquency at the branch. Escalate aged accounts, review restructuring options, and strengthen collections.',
      district: 'Analyse long-term delinquency across district offices. Identify branches with systemic aged-portfolio issues.',
      province: 'Assess province-wide long-term delinquency trends. Review whether credit policy or economic conditions are driving deterioration.',
      institution: 'Evaluate institutional delinquency management. Review write-off policies, recovery outsourcing, and portfolio segmentation.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=recoveries',
    category: 'Recovery',
  },
  {
    kpiCode: 'month3_recovery_achievements',
    kpiName: '3-Month Recovery Achievements',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review 3-month recovery achievements. Focus on collections from accounts 90-180 days past due.',
      district: 'Analyse 3-month recovery rates across district offices. Deploy specialised recovery teams where needed.',
      province: 'Assess province-wide 3-month recovery trends. Review whether portfolio seasoning is affecting recoverability.',
      institution: 'Evaluate institutional recovery performance. Review restructuring policies and early-delinquency interventions.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=recoveries',
    category: 'Recovery',
  },
  {
    kpiCode: 'product_diversification',
    kpiName: 'Product Diversification',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review product mix at the branch. Identify opportunities to cross-sell additional products to existing clients.',
      district: 'Analyse product diversification across district offices. Support branches with limited product penetration.',
      province: 'Assess province-wide product diversification. Review whether certain products are under-represented in specific regions.',
      institution: 'Evaluate institutional product strategy. Review new-product development and market segmentation.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=products',
    category: 'Products',
  },
  {
    kpiCode: 'product_risk_score',
    kpiName: 'Product Risk Score',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review product risk at the branch. Strengthen credit assessment for higher-risk products and monitor early warning signals.',
      district: 'Analyse product risk across district offices. Identify branches with elevated risk concentrations.',
      province: 'Assess province-wide product risk. Review whether risk appetite is being exceeded in certain segments.',
      institution: 'Evaluate institutional risk framework. Review risk appetite statements, concentration limits, and stress-testing.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=risk',
    category: 'Risk',
  },
  {
    kpiCode: 'roll_rate_control',
    kpiName: 'Roll Rate Control',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review roll-rate trends at the branch. Strengthen early-delinquency interventions and restructure before accounts age.',
      district: 'Analyse roll-rate control across district offices. Identify branches with deteriorating migration patterns.',
      province: 'Assess province-wide roll-rate trends. Review whether portfolio seasoning or macro conditions are driving migration.',
      institution: 'Evaluate institutional roll-rate strategy. Review early-warning systems, restructuring policies, and recovery triggers.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=recoveries',
    category: 'Recovery',
  },
  {
    kpiCode: 'yield_achievements',
    kpiName: 'Yield Achievements',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review yield performance at the branch. Optimise interest rate structures and reduce concessionary lending.',
      district: 'Analyse yield across district offices. Identify branches with below-market yields and review pricing strategies.',
      province: 'Assess province-wide yield trends. Review product pricing and client mix to identify yield improvement opportunities.',
      institution: 'Evaluate institutional yield strategy. Review pricing policy, risk-based pricing, and product margin targets.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=revenue',
    category: 'Revenue',
  },
  {
    kpiCode: 'revenue_achievements',
    kpiName: 'Revenue Achievements',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review revenue performance at the branch. Increase fee income, optimise product mix, and reduce waivers.',
      district: 'Analyse revenue across district offices. Identify branches with revenue leaks and deploy targeted interventions.',
      province: 'Assess province-wide revenue trends. Review whether product mix or pricing is constraining revenue growth.',
      institution: 'Evaluate institutional revenue strategy. Review fee schedules, product profitability, and revenue diversification.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=revenue',
    category: 'Revenue',
  },
  {
    kpiCode: 'profitability_contribution',
    kpiName: 'Profitability Contribution',
    target: 100,
    warningThreshold: 76,
    criticalThreshold: 60,
    higherIsBetter: true,
    severityRules: {
      healthy: (current) => current >= 90,
      low: (current) => current >= 76 && current < 90,
      medium: (current) => current >= 60 && current < 76,
      high: (current) => current >= 40 && current < 60,
      critical: (current) => current < 40,
    },
    recommendedActions: {
      branch: 'Review branch profitability. Reduce non-productive costs, improve yield, and optimise staffing.',
      district: 'Analyse profitability across district offices. Identify branches with persistent losses and develop turnaround plans.',
      province: 'Assess province-wide profitability. Review whether certain products or regions are structurally unprofitable.',
      institution: 'Evaluate institutional profitability strategy. Review cost structure, pricing, and product-portfolio profitability.',
    },
    applicableRoles: ['branch', 'district', 'province', 'institution'],
    route: '/lms/kpi-dashboard?tab=profitability',
    category: 'Finance',
  },
];

export function getRuleByKpiCode(kpiCode: string): KPIGuidanceRule | undefined {
  return KPI_GUIDANCE_RULES.find((r) => r.kpiCode === kpiCode.toLowerCase().replace(/\s+/g, '_'));
}

export function getRulesForRole(role: ManagerRoleTier): KPIGuidanceRule[] {
  return KPI_GUIDANCE_RULES.filter((r) => r.applicableRoles.includes(role));
}
